name: Spell Check

on:
  pull_request:
    branches: [main]

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          files: |
            **/*.{ts,tsx,js,md,json,yaml,yml}
          incremental_files_only: true
          strict: true
